#!/bin/sh
##############################
# bubbles - Draw "bubbles" diagram (connectivity graph) for given Allstar node "seed"
#
# HISTORICAL INFORMATION -
#
# 2018-12-12  msipin  Created.
# 2018-12-13  msipin  Added annotations to each node. Added color gradient to each node.
#                     Built output into temporary location, so it can run in the
#                     background while others use the "final" SVG file.
##############################

SEED_NODE_NUMBER=""

# This is the URL to the output (SVG) diagram
outsvg="/srv/http/supermon/bubbles.svg"

outdot="/dev/shm/bubbles.$$.dot"
# This is the temporary outpuf file for building the SVG diagram
outsvg2="/dev/shm/bubbles.$$.svg"

trap "rm -f $outdot $outsvg2; exit 0" 0 1 2 3 6 12 15


rm -f $outdot

# Starting NODE number (usually is *YOUR* node number!) - unless you
# override it on the command line!
if [ $# -lt 1 ]
then
	SEED_NODE_NUMBER=`echo $NODE1`
fi

while [ $# -ge 1 ]
do
    SEED_NODE_NUMBER=`echo $SEED_NODE_NUMBER $1`
    shift 1
done

##echo "DEBUG: SEED_NODE_NUMBER: [${SEED_NODE_NUMBER}]"
##exit 2


rm -f $outdot
####################################
# SMALL -
#        pad="0.5";
#        overlap=scalexy;
#        nodesep=0.6;
####################################
# HUGE -
#        pad="0.5";
#        splines=true;
#        overlap=false;
#        nodesep=0.6;
####################################
# FROM ODROID DURING CARNA-BOTNET-MAPPING -
#   pad="0.5";
#   ranksep="2";
#   splines=true;
#   overlap=scalexy;
#   nodesep=0.6;
####################################
# ACTUAL -
#   pad="0.5";
#   overlap=scalexy;
#   nodesep=0.6;
####################################

cat << EOF >> $outdot
digraph {
edge [dir="both"];
concentrate=true;
overlap=scalexy;
splines=true;
overlap=false;
nodesep=0.6;
forcelabels=true;
EOF

astar -b $SEED_NODE_NUMBER >> $outdot

# Add annotations to each node
#
# use "white:lightblue" for "nominal"
#    <stop offset="1" style="stop-color:lightblue;stop-opacity:1.;"/>
# use "white:lightyellow" for "short transmit"
#    <stop offset="1" style="stop-color:lightyellow;stop-opacity:1.;"/>
# use "white:green" for "transmit"
#    <stop offset="1" style="stop-color:green;stop-opacity:1.;"/>

astar $SEED_NODE_NUMBER | sed "s/ /|/" | awk -F"|" '{
printf "%s [label=\"%s - %s\n%s\", style=filled, fillcolor=\"white:lightblue\"];\n", $1, $3, $1, $5;
}' >> $outdot

echo "}" >> $outdot

rm -f $outsvg2
neato -Tsvg  $outdot | awk '{

if ($1 == "<svg")  print $1;
else print $0;

}' >> $outsvg2
mv $outsvg2 $outsvg


exit 0

