#!/bin/sh
#####################################
# getdb - Get the current list of all active Allstar nodes and
#         save it to a local file with delimited fields for use by
#         other tools.
#
# HISTORICAL INFORMATION -
#
#  2018-12-12  msipin  Created.
#  2018-12-13  msipin  Added "-h" command-line argument to show where file ("db") gets stored.
#                      Only delete current file if "lynx" command can be found - to ensure that
#                      a new one can be generated! Changed name of "db" file so its purpose
#                      will be more obvious - since it will be referenced across multiple tools!
#                      Moved callsign to 3rd field (swapped 3rd and 4th).
#  2018-12-18  msipin  Merge in the Allstar "asterisk node database", if found.
#                      (ROLLED BACK - too many duplicates)
#  2019-01-18  msipin  Fixed bug "if 0" on line 79 (now 80 because of this comment).
#
#  2019-02-11  msipin  Here are some resources within the "nominal" Allstar distribution that
#                      are related to building a node list -
#                              (RSYNC TO) allstarlink.org/connect-messages
#                              https://allstarlink.org/cgi-bin/allmondb.pl
#  2019-08-02  msipin  Fixed redirect of both stdout and stderr for systems that don't like the
#                      pipe-plus-ampersand (e.g. "|&").
#####################################

CMD="lynx"

# Local copy of Allstar node database
ALLSTAR_NODE_DB=/var/tmp/nodes.db

# (Possible) Local copy of "asterisk node database" (NOTE: MIGHT NOT EXIST!)
# TO-DO: IF FILE EXISTS - Stick a pipe ("|") character at the beginning of the line, 
#        and "join" this with ALLSTAR_NODE_DB contents for a "more complete" list.
ASTERISK_NODE_DB=/var/log/asterisk/astdb.txt


tmp_file1="/var/tmp/blah1.out"
tmp_file2="/var/tmp/blah2.out"
tmp_file3="/var/tmp/blah3.out"


trap "rm -f $tmp_file1 $tmp_file2 $tmp_file3; exit 0" 0 1 2 3 6 12 15



if [ $# -ge 1 -a ""$1"" = "-h" ]
then
	echo
	echo "Allstar node database location: $ALLSTAR_NODE_DB"
	echo
	exit 1
fi



rslt=`which $CMD 2>&1 | grep -v "which: no"`
if [ -z ""$rslt"" ]
then
	echo
	echo "Error: Don't have $CMD on this system (or somewhere in your \$PATH)!"
	echo
	echo "(Possibly install with 'pacman -S ${CMD}')"
	echo
	exit 2
fi

# Only remove any old one if the command(s) for building a new one can be found on this system!
rm -f $ALLSTAR_NODE_DB

rm -f $tmp_file1 $tmp_file2 $tmp_file3



$CMD -dump -width 500 http://stats.allstarlink.org/ | sed "s/\[[0-9]*\]/|/g" | sed "s/|Map |Bubble /|/" | sed "s/ |/|/g" | sed "s/ [0-9]*S$//" | sed "s/ [0-9]*M$//" | sed "s/ [0-9]*H$//" | sed "s/ [0-9]*D$//" | sed "s/^  |/|/" | awk -F"|" '{ if (NF > 3) print $0 }' | awk -F"|" '{

for (i=2;i<=NF;i++) {
    if (i == 3) printf "%s%s", FS, $4;
    else if (i == 4) printf "%s%s", FS, $3;
    else printf "%s%s", FS, $i;
};
printf "\n";

}' >  $ALLSTAR_NODE_DB


if [ 0 ]
then
	rm -f $tmp_file1 $tmp_file2 $tmp_file3

	# If it exists, merge the "Asterisk" node database with the one we just developed
	if [ -s $ASTERISK_NODE_DB ]
	then
		cat $ASTERISK_NODE_DB | sed "s/^/|/" | awk -F"|" '{ if ((NF >= 5) && ($2 != "1000")) print $0; }' | sed "s/|<None>|/||/" | sort -u > $tmp_file1
		diff $ALLSTAR_NODE_DB $tmp_file1 | grep "^>" | sed "s/> //" > $tmp_file2
		cat $ALLSTAR_NODE_DB $tmp_file2 | sort -u > $tmp_file3

		mv $tmp_file3 $ALLSTAR_NODE_DB
	fi
fi


# Display how many records retrieved
echo
wc -l $ALLSTAR_NODE_DB | awk '{ printf "%s records saved to %s\n", $1, $2; }'
echo

exit 0

